### ISSUE TITLE
Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#101]
Getting the following error on executing specs
```
new Test(step.fn, parameters, timeout).run().then(
                ^

TypeError: Cannot read property 'fn' of undefined
    at Object.executeStep [as step] (...\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-01-16\src\executor.js:46:17)
    at MessageProcessor.executeStep (...\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-01-16\src\message-processor.js:34:26)
    at MessageProcessor.getResponseFor (...\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-01-16\src\message-processor.js:197:40)
    at ExecutionConnection.<anonymous> (...\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-01-16\src\gauge.js:23:17)
    at ExecutionConnection.emit (events.js:159:13)
    at Socket.messageHandler (...\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-01-16\src\connection.js:17:10)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)

        Error Message: write tcp 127.0.0.1:65478->127.0.0.1:65483: use of closed network connection
        Stacktrace:


        Error Message: write tcp 127.0.0.1:65478->127.0.0.1:65483: use of closed network connection
        Stacktrace:


        Error Message: write tcp 127.0.0.1:65478->127.0.0.1:65483: use of closed network connection
        Stacktrace:


        Failed Step: goto definition of step "Concept2" in "/specs/concept_definition.spec" at "4" and "4" should give details "specs/gotodefinition/concept.yaml"
        Specification: specs\gotodefinition\goto a concept.spec:8
        Error Message: Connection closed [127.0.0.1:65483] cause: read tcp 127.0.0.1:65478->127.0.0.1:65483: wsarecv: An existing connection was forcibly closed by the remote host.
        Stacktrace:


    Error Message: write tcp 127.0.0.1:65478->127.0.0.1:65483: use of closed network connection
    Stacktrace:


  Error Message: write tcp 127.0.0.1:65478->127.0.0.1:65483: use of closed network connection
  Stacktrace:
```
**Steps to replicate**
* Run spec - Goto a step definition from project -
[gauge-lsp-tests.zip](https://github.com/getgauge/gauge-js/files/1650782/gauge-lsp-tests.zip)

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-19
Commit Hash: 0c66ca4

Plugins
-------
js (2.1.1.nightly-2018-01-16)
```

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge-js nightly >= 02/02/18

**Comment by sguptatw** [comment]
Nightly gauge-js is not available 02/02/18 
The latest Gauge-js nightly is Jan 16th 2017

<img width="410" alt="jan16th" src="https://user-images.githubusercontent.com/6310197/35789301-48d845e4-0a61-11e8-922c-a0b4bbd96f17.png">

**Comment by Apoorva-GA** [comment]
I have triggered the nightly. Should be available in nightly 05/02/18.
