### ISSUE TITLE
Unable to run gauge specs

### ISSUE THREAD

**Issue by sswaroopgupta** [getgauge/gauge-js#105]
**Expected behavior**
Should be able to run gauge specs

**Actual behavior**
Getting error
```
module.js:442
    throw err;
    ^

Error: Cannot find module 'inspector'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/twist/.gauge/plugins/js/2.1.1.nightly-2018-02-05/src/message-processor.js:13:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Failed to start gauge API: Timed out connecting to [::]:50638
```
**Steps to replicate**
* Create a new `gauge-js` project
* run `gauge specs`

**Version**
OSX - 10.9.5
```
auge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
dotnet (0.0.1.nightly-2018-02-05)
html-report (1.1.0)
js (2.1.1.nightly-2018-02-05)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by nehashri** [comment]
@sguptatw Which version of npm and nodejs are you using?

**Comment by sguptatw** [comment]
@nehashri 
Node version 6.3. This is lower than the expected node version. Can the messaging be better than `inspector` error?

**Comment by zabil** [comment]
https://nodejs.org/docs/v0.10.12/api/process.html#process_process_version

**Comment by nehashri** [comment]
@sguptatw That may be hard, as some dependencies have failed to install because of lower node version. Checking for such dependencies before they are used may not be the best idea. Instead we could check for the version before starting the runner itself (runner should not start if node version is not satisfied). Not sure how helpful this would be though
