### ISSUE TITLE
Runner should not scan the whole project root for files

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-js#114]
Ref: #82

Currently, the `gauge-js` runner scan the whole `GAUGE_PROJECT_ROOT` including `reports`, `node_modules`, `.gauge` , `.git` (worst part) etc.
After that, it filters the `step` implementations file using `micromatch` with user-defined regex.

But `gauge-js` should not even walk into these dirs.

## Proposals -
* Use a env to define which directories to look into (like `gauge-python` Ref: https://github.com/getgauge/gauge-python/blob/46225cc1064fa77411b5acb1ba0ed47f6645811b/skel/python.properties#L3)
* Add an env to exclude dirs.
* Use `gauge_exclude_dir` env to exclude dir

thoughts/comments/ideas ??

**Comment by sguptatw** [comment]
> Note The above issue seems to cause the following error 
```
Failed while loading proto file.
 { Error: ENOENT: no such file or directory, stat '/Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/reports/html-report/html-report'
    at Object.fs.statSync (fs.js:968:11)
    at /Users/vagrant/.gauge/plugins/js/2.1.0/src/file-util.js:16:21
    at Array.forEach (<anonymous>)
    at walk (/Users/vagrant/.gauge/plugins/js/2.1.0/src/file-util.js:14:25)
    at /Users/vagrant/.gauge/plugins/js/2.1.0/src/file-util.js:20:26
    at Array.forEach (<anonymous>)
    at walk (/Users/vagrant/.gauge/plugins/js/2.1.0/src/file-util.js:14:25)
    at /Users/vagrant/.gauge/plugins/js/2.1.0/src/file-util.js:20:26
    at Array.forEach (<anonymous>)
    at walk (/Users/vagrant/.gauge/plugins/js/2.1.0/src/file-util.js:14:25)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/vagrant/go-agent-17.4.0/pipelines/Ruby-LSP-Tests/reports/html-report/html-report' }
Error ----------------------------------

Failed to start gauge API: Timed out connecting to [::]:55257

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	darwin, 0.9.8, 77c642d
	html-report (4.0.4), java (0.6.7), js (2.1.0), ruby (0.4.3), screenshot (0.0.1), xml-report (0.2.1)
```
Reference - Ruby LSP tests on darwin

**Comment by BugDiver** [comment]
Add env STEP_IMPL_DIR to specify source dir. #122
