### ISSUE TITLE
Should handle script errors better

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#119]
**Expected behavior**
If the script corresponding to a step has errors, it should be handled gracefully. A message should be displayed stating the reason of failure without exceptions.

**Actual behavior**
Unexpected behavior during execution

**Steps to replicate**
* Steps timeout if there is a parameter mismatch - https://github.com/getgauge/gauge-js/issues/98
* Duplicate parameter names causes an exception
```
Error executing tests\step_implementation.js
Trace: tests\step_implementation.js:22
step("two <one> <two>", function(one, one) {
                                      ^^^

SyntaxError: Duplicate parameter name not allowed in this context
    at createScript (vm.js:80:10)
    at Object.runInContext (vm.js:132:10)
    at VM.run (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\vm.js:54:8)
    at VM.runFile (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\vm.js:69:8)
    at C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\impl-loader.js:11:8
    at Array.forEach (<anonymous>)
    at Object.loadImpl [as load] (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\impl-loader.js:8:62)
    at startExecution (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\message-processor.js:64:15)
    at MessageProcessor.executeBeforeSuiteHook (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\message-processor.js:78:5)
    at MessageProcessor.getResponseFor (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\message-processor.js:252:40)
    at VM.run (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\vm.js:57:13)
    at VM.runFile (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\vm.js:69:8)
    at C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\impl-loader.js:11:8
    at Array.forEach (<anonymous>)
    at Object.loadImpl [as load] (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\impl-loader.js:8:62)
    at startExecution (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\message-processor.js:64:15)
    at MessageProcessor.executeBeforeSuiteHook (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\message-processor.js:78:5)
    at MessageProcessor.getResponseFor (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\message-processor.js:252:40)
    at ExecutionConnection.<anonymous> (C:\Users\sswaroop\AppData\Roaming\gauge\plugins\js\2.1.1.nightly-2018-02-14\src\gauge.js:23:17)
    at ExecutionConnection.emit (events.js:159:13)
```
**Version**
```
Gauge version: 0.9.8.nightly-2018-02-28
Commit Hash: d997b9a

Plugins
-------
js (2.1.1.nightly-2018-02-14)
```

**Comment by zabil** [comment]
Closing this as this should be handled as a part of https://github.com/getgauge/gauge-js/issues/98
