### ISSUE TITLE
Project created using JS webdriver template should run successfully

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#124]
**Actual behavior**
Getting the following error
```
[ParseError] C:\work\testFolder\jstest\webdriver1\specs\example.spec:1 Spec should have atleast one scenario => ''
[ParseError] C:\work\testFolder\jstest\webdriver1\specs\example.spec:9 Multiple spec headings found in same file => '# Get Started'

  Error Message: Error: connect ECONNREFUSED 127.0.0.1:4444
  Stacktrace:
  Error: connect ECONNREFUSED 127.0.0.1:4444
      at new RuntimeError (node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
      at Request._callback (node_modules\webdriverio\build\lib\utils\RequestHandler.js:327:43)
      at self.callback (node_modules\request\request.js:186:22)
      at Request.emit (events.js:159:13)
      at Request.onRequestError (node_modules\request\request.js:878:8)
      at ClientRequest.emit (events.js:164:20)
      at Socket.socketErrorListener (_http_client.js:389:9)
      at Socket.emit (events.js:159:13)
      at emitErrorNT (internal/streams/destroy.js:64:8)
```
**Steps to replicate**
* `gauge init js_webdriver`
* `npm install` on the generated folder
* `gauge run specs`

> The above error occurs
**Version**
```
Gauge version: 0.9.8.nightly-2018-03-05
Commit Hash: 63aeb3b

Plugins
-------
js (2.1.1.nightly-2018-02-14)
screenshot (0.0.1)
```

**Comment by zabil** [comment]
Run selenium standalone server before running the specs

**Comment by sguptatw** [comment]
Should not get Parse errors
```
[ParseError] C:\work\testFolder\jstest\webdriver1\specs\example.spec:1 Spec should have atleast one scenario => ''
[ParseError] C:\work\testFolder\jstest\webdriver1\specs\example.spec:9 Multiple spec headings found in same file => '# Get Started'
```

**Comment by sguptatw** [comment]
Fixed with the latest templates
