### ISSUE TITLE
Should not timeout while debugging

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#128]
The test_timeout configuration must be ignored while debugging

**Current behavior**
It times out while debugging
```
Stacktrace: 
            Error: Timed out
                at Timeout.<anonymous> (/Users/sswaroop/.gauge/plugins/js/2.2.0.nightly-2018-03-12/src/test.js:43:23)
                at ontimeout (timers.js:458:11)
                at tryOnTimeout (timers.js:296:5)
                at Timer.listOnTimeout (timers.js:259:5)
```

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-09
Commit Hash: c895c3f

Plugins
-------
html-report (4.0.3)
java (0.6.6)
js (2.2.0.nightly-2018-03-12)
screenshot (0.0.1)
```

**Comment by Apoorva-GA** [comment]
This is not replicable on JS sample project.

**Comment by Apoorva-GA** [comment]
The above issue is replicable on js_webdriver project.

Fix should be available in gauge-js nightly >= 14/03/18

**Comment by sguptatw** [comment]
Blocked because of https://github.com/getgauge/gauge-vscode/issues/207
