### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#137]
**Expected behavior**
Should not get exception opening a project

**Actual behavior**
```
/Users/sswaroop/.gauge/plugins/js/2.2.0.nightly-2018-03-29/src/message-processor.js:263
  this.processors[request.messageType].call(this, request);
                                       ^

TypeError: Cannot read property 'call' of undefined
    at MessageProcessor.getResponseFor (/Users/sswaroop/.gauge/plugins/js/2.2.0.nightly-2018-03-29/src/message-processor.js:263:40)
    at ExecutionConnection.<anonymous> (/Users/sswaroop/.gauge/plugins/js/2.2.0.nightly-2018-03-29/src/gauge.js:31:17)
    at ExecutionConnection.emit (events.js:160:13)
    at Socket.messageHandler (/Users/sswaroop/.gauge/plugins/js/2.2.0.nightly-2018-03-29/src/connection.js:20:12)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:602:20)
10:21:11.807 notif #0: initialized: Connection closed [127.0.0.1:60852] cause: EOF
```
**Steps to replicate**
* Open the gauge-lsp-tests in VSCode

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-05
Commit Hash: 51a094a

Plugins
-------
html-report (4.0.4.nightly-2018-03-30)
java (0.6.7.nightly-2018-04-05)
js (2.2.0.nightly-2018-03-29)
report-seed (0.0.1)
ruby (0.4.3.nightly-2018-04-05)
screenshot (0.0.1)
```

**Comment by sguptatw** [comment]
Fixed with 
```
Gauge version: 0.9.8.nightly-2018-04-11
Commit Hash: 4d314ef

Plugins
-------
html-report (4.0.4.nightly-2018-04-11)
js (2.2.0.nightly-2018-04-13)
screenshot (0.0.1)
```
