### ISSUE TITLE
Failed to load implementations

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#138]
**Expected behavior**
Should be able to load implementations

**Actual behavior**
```
Failed to load implementations from ...\gauge-lsp-tests\data\codecomplete\tests
...\gauge\plugins\js\2.2.0.nightly-2018-03-29\src\gauge.js:35
      throw err;
      ^

Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:53856)
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at internalConnect (net.js:987:16)
    at net.js:1087:9
    at process._tickCallback (internal/process/next_tick.js:150:11)
```
**Steps to replicate**
* Run LSP tests `gauge run specs`
> This error occurs on trying to open a project

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-06
Commit Hash: ac32b86

Plugins
-------
csharp (0.10.3.nightly-2018-04-06)
html-report (4.0.4.nightly-2018-03-28)
js (2.2.0.nightly-2018-03-29)
```

**Comment by zabil** [comment]
Closing this as an old issue. This may be fixed in the newer releases. 
Will reopen if it still needs fixing.

**Comment by sohaleKing** [comment]
its not fixed even now! 3 years after
