### ISSUE TITLE
Deleting a file gives connection unavailable

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#143]
**Expected behavior**
Should not get connection error

**Actual behavior**
Getting 
```
18:41:09.122 --> notif: workspace/didChangeWatchedFiles: {"changes":[{"uri":"file:///.../jstest/basic5/tests/step-implementation.js","type":3}]}
fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '...\tests\step-implementation.js'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at LspServerHandler.cacheFileResponse (...\gauge\plugins\js\2.2.0.nightly-2018-04-20\src\message-processor.js:252:36)
    at LspServerHandler.cacheFile (...\plugins\js\2.2.0.nightly-2018-04-20\src\lsp-server.js:25:34)
    at Object.wrapper [as func] (...\plugins\js\2.2.0.nightly-2018-04-20\node_modules\lodash\lodash.js:4968:19)
    at ...\gauge\plugins\js\2.2.0.nightly-2018-04-20\node_modules\grpc\src\server.js:592:13
``` 
**Steps to replicate**
* Create a `gauge-js` project
* Delete an implementation file
* Open a spec
* All steps are marked with grpc connection error

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-26
Commit Hash: 5bd699e

Plugins
-------
html-report (4.0.4.nightly-2018-04-11)
java (0.6.7.nightly-2018-04-24)
js (2.2.0.nightly-2018-04-20)
python (0.3.0.nightly-2018-04-25)
ruby (0.5.0.nightly-2018-04-16)
xml-report (0.2.1.nightly-2018-04-05)
```

**Comment by BugDiver** [comment]
Fixing #141  Should fix this as well.
