### ISSUE TITLE
Debugging point on a step/hook definition gives timeout

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#150]
**Expected behavior**
Should not get timeout.

**Actual behavior**
Getting 
```Error executing tests/step_implementation.js
Trace: Error: Script execution timed out.
    at Script.runInContext (vm.js:102:20)
    at Object.runInContext (vm.js:280:6)
    at VM.run (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/vm.js:58:8)
    at VM.runFile (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/vm.js:73:8)
    at /Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/impl-loader.js:9:8
    at Array.forEach (<anonymous>)
    at Object.loadImpl [as load] (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/impl-loader.js:6:29)
    at startExecution (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/message-processor.js:66:15)
    at Timeout._onTimeout (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/message-processor.js:78:30)
    at ontimeout (timers.js:427:11)
    at VM.run (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/vm.js:61:13)
    at VM.runFile (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/vm.js:73:8)
    at /Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/impl-loader.js:9:8
    at Array.forEach (<anonymous>)
    at Object.loadImpl [as load] (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/impl-loader.js:6:29)
    at startExecution (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/message-processor.js:66:15)
    at Timeout._onTimeout (/Users/sswaroop/.gauge/plugins/js/2.3.1.nightly-2018-05-23/src/message-processor.js:78:30)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
```

**Steps to replicate**
* Create a `gauge-js` project
* Add a debugger point on the definition of step and hook
* Start debugging
> When the debug point reaches the definition, click continue. The above error is thrown

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-23
Commit Hash: cf46420

Plugins
-------
js (2.3.1.nightly-2018-05-23)
```

**Comment by sguptatw** [comment]
Working as expected in
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
js (2.3.2.nightly-2018-06-19)
```
