### ISSUE TITLE
Should handle Chromium not available gracefully

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#174]
**Expected behavior**
When `SKIP_CHROMIUM_DOWNLOAD` is used to install taiko, running gauge-taiko projects should give an error that a valid `EXECUTABLE_PATH` of chromium should be provided or taiko should be installed without skipping chromium download.

**Actual behavior**
When `SKIP_CHROMIUM_DOWNLOAD` is used to install taiko, running gauge taiko specs are throwing few Exceptions
```
Unable to require module 'taiko' in .../js-taiko/tests/alert.js
Trace: Error: Cannot find module 'taiko'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at .../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/req-manager.js:33:54
    at Req.load (.../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/req-manager.js:39:5)
    at fn (.../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/req-manager.js:50:20)
    at .../js-taiko/tests/alert.js:3:5
    at Script.runInContext (vm.js:107:20)
    at Object.runInContext (vm.js:285:6)
    at VM.run (.../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/vm.js:58:8)
    at .../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/req-manager.js:36:15
    at Req.load (.../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/req-manager.js:39:5)
    at fn (.../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/req-manager.js:50:20)
    at .../js-taiko/tests/alert.js:3:5
    at Script.runInContext (vm.js:107:20)
    at Object.runInContext (vm.js:285:6)
    at VM.run (.../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/vm.js:58:8)
    at VM.runFile (.../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/vm.js:73:8)
    at .../.gauge/plugins/js/2.3.2.nightly-2018-09-13/src/impl-loader.js:9:8
    at Array.forEach (<anonymous>)
Error executing tests/alert.js
Trace: .../js-taiko/tests/alert.js:2
    alert,accept
...

Error Message: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
        Stacktrace:


        Failed Step: Navigate to "https://react-shopping-cart-67954.firebaseapp.com/"
        Specification: specs/alert.spec:5
        Error Message: Connection closed [127.0.0.1:52293] cause: EOF
        Stacktrace:


    Error Message: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
    Stacktrace:


  Error Message: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
  Stacktrace:


# Browser Action
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
# Getting Started with Gauge
# Page Actions
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
# Proximity Selectors
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
# Selectors
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
# API

  Error Message: write tcp 127.0.0.1:52292->127.0.0.1:52293: use of closed network connection
  Stacktrace:
```
**Steps to replicate**
* Project https://github.com/getgauge-examples/js-taiko
* `npm uninstall taiko` inside js-taiko
* Get the latest of https://github.com/getgauge/taiko/
* `npm uninstall taiko -g`
* Inside taiko folder `SKIP_CHROMIUM_DOWNLOAD=true npm install . -g`
* In project `js-taiko` run `gauge run`
> The above exceptions are thrown

**Version**
```
commit - 03b5c4a65a9d51fb0b95e4e459c77a49be19e917
```
> Blocks https://github.com/getgauge/taiko/issues/246

**Comment by NivedhaSenthil** [comment]
Taiko has to be installed as a local module within js-taiko or has to be linked to global installation. Seems like from the above steps it is not installed locally, try `npm install` within js-taiko  or `npm link taiko` to link to the global installation

**Comment by sguptatw** [comment]
Even after `npm install` within js-taiko, this issue is replicable. 

**Steps to replicate**
Same as mentioned in the original issue description

**Comment by sguptatw** [comment]
When Executable Path is invalid getting Error call openBrowser() ... 
This is tracked as a separate issue https://github.com/getgauge/taiko/issues/253
