### ISSUE TITLE
There is no detail error trace indicating which line of code cause the timeout?

### ISSUE THREAD

**Issue by windyliu1118** [getgauge/gauge-js#307]
When I execute my test, I got the error below:
```
auto % gauge run --env staging1 --tags "add_tpl_position" specs
# 01 Adding Positions
  ## Add a position from position template      ScenarioInfo {
tags: [ 'add_tpl_position' ],
name: 'Add a position from position template' }
 ✔ ✔ ✔ ✔ ✘
        Failed Step: Verify the existing stage and confirm
        Specification: specs/01_positions.spec:11
        Error Message: Error: Timed out
        Stacktrace: 
        Error: Timed out
            at Timeout.<anonymous> (/Users/windyliu/.gauge/plugins/js/2.3.7/src/test.js:43:23)
            at ontimeout (timers.js:498:11)
            at tryOnTimeout (timers.js:323:5)
            at Timer.listOnTimeout (timers.js:290:5)
Successfully generated html-report to => /Users/windyliu/Workstream/workstream-auto/reports/html-report/index.html
Successfully generated xml-report to => /Users/windyliu/Workstream/workstream-auto/reports/xml-report
Specifications: 1 executed      0 passed        1 failed        0 skipped
Scenarios:      1 executed      0 passed        1 failed        0 skipped
Total time taken: 1m28.159s
Updates are available. Run `gauge update -c` for more info.
```
But the error trace only indicate which step failed in spec file, but it didn't show me which line of code in that step cause the failure. Without the exact code info, it's not easy for me to debug.
Is there a way to show which line of code in the step causing the error?

**Comment by windyliu1118** [comment]
the spec file as below:
```
# 01 Adding Positions
## Add a position from position template
Tags: add_tpl_position
* Navigate to positions page
* Click Add position button on Positions page
* Choose a template "Waiter/Waitress" 
* Enter "Shanghai" and "Design" in the template
* Verify the existing stage and confirm
* Publish position "Waiter/Waitress" at "Shanghai" and Verify the Share position dialog
* Navigate to positions page
* Search the published position "Waiter/Waitress" at "Shanghai" and "Design" and do verification
```

the related js file is as below:
```
step("Navigate to positions page", async () => {
    await waitFor(20000);
    await click(link({class: 'jsa-positions-page-button'}));
    //await waitFor(30000);
    assert.ok(await text('All positions').exists());
});
step("Click Add position button on Positions page", async () => {
    await click(button('Add position'));
    assert.ok(await text('Choose a template to get started').exists());
});
step("Choose a template <template_name>", async (template_name) => {
    await click(template_name);
    assert.ok(await text('Job details').exists());
    assert.ok(await textBox({value: template_name}).exists());
});
step("Enter <location> and <department> in the template", async (location, department) => {
    await write(location, into(textBox(near('Location'))));
    //debugger;
    await click($(`//*[text()='${location}']`));
     //await click($(`//*[text()='Shanghai']`));
    await write(department, into(textBox(near('Department'))));
    //debugger;
    // await click($(`//*[text()='Design']`));
    await click($(`//*[text()='${department}']`));
    await click('Next');
    assert.ok(await text("Hiring process").exists());
});
step("Verify the existing stage and confirm", async () => {
    assert.ok(await text('Application form stage').exists());
    assert.ok(await text('Application form stage', below('Application')).exists());
    assert.ok(await text('Custom stage', below('Additional Information')).exists());
    assert.ok(await text('Scheduling stage', below('Application Complete')).exists());
    assert.ok(await text('Custom stage', below('Onsite Interview')).exists());
    await click('Next');
    assert.ok(await text('Job boards').exists());
});
step("Publish the position", async () => {
    await click('Create position');
    assert.ok(await text('Share position').exists());
    await click(button({class:"ant-modal-close"}));
    assert.ok(await text("Waiter/Waitress at Shanghai").exists());
    assert.ok(text("Add applicant").exists());
});
step("Publish position <position> at <location> and Verify the Share position dialog", async (position, location) => {
    await click('Create position');
    await waitFor(5000);
    assert.ok(await text('Share position').exists());
    assert.ok(await text("Share", toLeftOf("Referral"), toRightOf("Link")).exists());
    assert.ok(await text("Link to share", toLeftOf("Open in new tab")).exists());
    assert.ok(await text("Text to apply instructions", toLeftOf("US")).exists());
    assert.ok(await text("Get Text-to-apply Poster", toLeftOf("New")).exists());
    await click(button({class:"ant-modal-close"}));
    const position_text = position + " at " + location
    assert.ok(await text(position_text).exists());
    assert.ok(await text("Add applicant").exists());
});
step("Search the published position <position> at <location> and <department> and do verification", async (position, location, department) => {
    await write(position, into(textBox({placeholder: "Search for position"})));
    await click(button(near("All positions")));
    assert.ok(await link(position).exists());
    assert.ok(await text(location, toLeftOf(department), toRightOf(position)).exists());
    assert.ok(await text("0", toLeftOf("0"), toRightOf("0")).exists());
    assert.ok(await image({src: "/static/browser.42cc0c6c.svg"}).exists());
    assert.ok(await text("on", toLeftOf("Public")).exists());
    assert.ok(await $("div.workstream-action-popover-wrapper").exists());
});
```

**Comment by sriv** [comment]
The timeout is thrown because the step took more than [`test_timeout`](https://docs.gauge.org/configuration.html?os=windows&language=javascript&ide=vscode#js-properties-2) set in `js.properties`. This means that the implementation took more time than what was set in `test_timeout`, and not that any of the statements themselves threw a timeout. Ideally, your `test_timeout` should be greater than the worst case execution timeouts of your tests.

For example, this test:

```
step("Choose a template <template_name>", async (template_name) => {
    await click(template_name); // took 3000ms
    assert.ok(await text('Job details').exists()); // took 4000ms
    assert.ok(await textBox({value: template_name}).exists()); // took 4000ms
});
```
In the above example, the individual action's all are under the default value of  `navigationTimeout` (=5000ms) but they add up to be 11000ms, which is > `test_timeout` of gauge-js, causing gauge-js to throw a timeout error, not Taiko.

**Comment by windyliu1118** [comment]
@sriv  if in this case, how much time to be set for the ```test_timeout``` in js.properties you will suggest?

**Comment by sriv** [comment]
That would depend on your application, the number of actions you may have in a test that depend on `navigationTimeout` etc. Essentially, if you application has some minimum load time in an environment, that needs to be factored in. (note that taiko's navigation relies on all resources to be loaded, so if you are using any resource that would slow down your page load, it would reflect on the navigation, and thus on the test). 

Rather than analyzing, I suppose a faster way is to do a few runs with various values of `test_timeout` and decide what is a reasonable configuration for your tests to be reliable.

**Comment by windyliu1118** [comment]
Thanks @sriv  for your suggestions, really helps a lot.

**Comment by sriv** [comment]
closing this, please feel free to comment if there's anything Taiko can do better.
