### ISSUE TITLE
js runner quit unexpectedly. Check logs for more details

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/gauge-js#411]
When there is an unhandled exception from user's code, gauge-js is getting terminated.

#### Steps to replicate:

1. `gauge init js`
2. 
```js
//add setTimeout and throw error like below in stepImplementation.js file
setTimeout(()=>{
  throw new Error('break gauge-js')
}, 2);
```
3. gauge run

#### Error

```
starting execution
/../simple-js/tests/step_implementation.js:14
throw new Error('break gauge-js')
^
Error: break gauge-js
at Timeout._onTimeout (/../simple-js/tests/step_implementation.js:14:9)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
Error ----------------------------------

[Gauge]
js runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	darwin, 1.1.6, f455126a
	csharp (0.10.6), dotnet (0.1.4), flash (0.0.1), html-report (4.0.12), java (0.7.13), js (2.3.14), json-report (0.3.1), python (0.3.10), ruby (0.5.3), screenshot (0.0.1), ts (0.1.0), xml-report (0.2.2)
```

**Comment by NivedhaSenthil** [comment]
Fixed in Gauge1.1.6.
